# Generated by Django 5.1.2 on 2024-10-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='storage_amount',
            field=models.IntegerField(default=0, verbose_name='Количество на складе'),
        ),
    ]
